version: '3'

services:
  # PHP + Apache service
  web:
    build: .
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  # MySQL service
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: rstw2023
      MYSQL_USER: rstw2023
      MYSQL_PASSWORD: rstw2023
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data: {}
